
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://health.c8bzwssqe1ja.ap-northeast-2.rds.amazonaws.com:3306/healthDB
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995849491979-4rlh0aej2ra9usadvr3h8q9ve68p9b7i.apps.googleusercontent.com
            client-secret: TCrb8Hlvdr47niw-5Aj_z2PL
            scope:
              - email
              - profile