
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1q2w3e4r!@
    url: jdbc:mysql://127.0.0.1/health
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995849491979-4rlh0aej2ra9usadvr3h8q9ve68p9b7i.apps.googleusercontent.com
            client-secret: TCrb8Hlvdr47niw-5Aj_z2PL
            scope:
              - email
              - profile